### ISSUE TITLE
Haskell for Mac

### ISSUE THREAD

**Issue by mchakravarty** [haskell-infra/hl#133]
What would be an appropriate way to list [Haskell for Mac](http://haskellformac.com) on the downloads page? One possible option would be another section with the headline "Integrated Development Environments" and a list of two bullet points, one for Leksah and one for Haskell for Mac.

What do you think?

I'm happy to provide a pull request, but I just want to do it in a way that everybody is fine with.

**Comment by mchakravarty** [comment]
One one hand, it should probably also list FP Complete's FP Haskell Center, but I believe they are planning to discontinue the IDE. If I'm mistake on that point, it of course ought to be included, too. (Even if it is not technically a download.)

**Comment by gbaz** [comment]
We're having some other discussions about the shape of the downloads page at the moment, and one thing we want to tackle is having some sort of "other distributions" section where H4M would be appropriate among other things. (for example Kronos Haskell: http://www.kronosnotebook.com/haskell and https://halcyon.sh/ maybe).

I'm not sure if we want an IDEs section on that page, or just a separate page. For some of this "additional stuff" we perhaps just want a link to then a community wiki page where stuff can be more freely added.

H4M is of course in a slightly weird spot as half-distribution half-ide due to the appstore policy questions, and so would be sort of multiply appropriate even if we _did_ have an IDE page.

Perhaps "Haskell Environments" is a different enough category than "Haskell Distributions" that we should have _two_ extra sections on the page?

In any case, this is all spitballing. If you're comfortable waiting a bit (measured in days, not weeks or months), what would be good is to first kick-off a discussion on the haskell-community list on some of the other aspects of the page (which we are planning) and then kick off the "how do we do the other stuff" discussion as auxiliary to that.

**Comment by mchakravarty** [comment]
That all makes a lot of sense. When you are saying kick off a discussion on the haskell-community list, do you mean that I should start this discussion or that you are about to do that anyway? In either case, I'm happy to help, where I can.

**Comment by gbaz** [comment]
We'll start one soon, I hope. If we don't, kick us :-P

**Comment by mchakravarty** [comment]
Will do! :)

**Comment by gbaz** [comment]
Ok, I think this is resolved now with a link to a wiki page with more options, at least for the time being.
