### ISSUE TITLE
getDirectoryContents: does not exist (No such file or directory)

### ISSUE THREAD

**Issue by kxxoling** [haskell-infra/hl#137]
Project is built successfully, but when I run ``dist/build/hl/hl`` would get the error below:

```
hl: hl/.cabal-sandbox/share/x86_64-osx-ghc-7.10.2/hl-0.0.0/static: getDirectoryContents: does not exist (No such file or directory)
```

What's different while building is, I failed to install text-icu via cabal.
Firstly, I don't have the C lib, so i installed it via HomeBrew.
But it fell again.
After searching with the error message, I found text-icu need to build with some special arguments.
So I installed separately with:  

```
cabal install text-icu --extra-lib-dirs=/usr/local/opt/icu4c/lib --extra-include-dirs=/usr/local/opt/icu4c/include
```

This worked well. Then I run ``cabal build``, without any error it works.
When I run ``dist/build/hl/hl``, this error came. And I did not find any help on the internet.
Anybody knows why it doesn't work?

My system is the newest Mac OS X 10.10, with haskell and cabal installed via HomeBrew.

**Comment by gbaz** [comment]
I just ran into this too -- it has nothing to do with icu, and only to do with looking for the `/static` directory in that location, which is not created.

It seems to be some sort of regression with however the core libraries used for finding static resources (I guess tied into yesod?) interact with cabal sandboxing.

(note this _used_ to work for me until recently when a number of things were upgraded).

The temporary workaround I settled on was to create that directory chain and copy the "/static" directory there for the app to find. Then, when I edit files in the real static directory, I copy it over again.

(One might think, and indeed I did, that creating a symbolic link would work. However, this caused some other form of error about nested symbolic links. Rather than tempt fate with a hardlink, which could maybe cause something to get deleted if the sandbox was wiped, I just shrugged and settled on the manual solution.)

Maybe @chrisdone  knows what could be really going on? (Note that this issue seems restricted just to sandboxing, so shouldn't affect our proper deploy at least).

**Comment by kxxoling** [comment]
@gbaz This really works, thanks! But it also should get an real fix.

**Comment by gbaz** [comment]
Ok, so if you go to https://github.com/haskell-infra/hl/blob/master/src/HL/Development.hs and manually just set development = True (i.e. get rid of the CPP stuff) then that also makes it work correctly.

I'm not sure what's supposed to define DEVELOPMENT flag, which is how it would work normally. But just tweaking that file by hand on your local setup isn't a bad option.

**Comment by gbaz** [comment]
I updated the build instructions to note that we should set the DEVELOPMENT flag, so that seems good enough here?
