### ISSUE TITLE
News/Events relation to Wiki

### ISSUE THREAD

**Issue by amigalemming** [haskell-infra/hl#145]
I want to add a new Event to https://www.haskell.org/news. The list of events at this page is quite outdated. I guess the events are too far away from the front page and from the top of the News page. The title "Event" links to https://wiki.haskell.org/Template:Main/Events. This contains current events, but that event list differs from the one shown at https://www.haskell.org/news. I tried to add the event to some of the files from https://github.com/haskell-infra/hl/ but I could not find a file containing the events listed at haskell.org/news. I only found Community.hs which contains the content of haskell.org/community.
So where can I add an event to haskell.org/news and is it possible to make it more obvious how to achieve that?

**Comment by gbaz** [comment]
Those events draw from a feed generated by http://haskellnews.org/grouped -- that in turn draws its events from the wiki.haskell.org page.

For some reason haskellnews.org isn't pulling and updating events properly (probably because of the transition of the wiki to wiki.haskell.org).

I guess we need @chrisdone to fix haskellnews.org? Alternately, we could rewrite the events section to draw directly from the wiki... I'm open to either, and have just been too otherwise busy to follow up...

**Comment by beerendlauwers** [comment]
That seems the most plausible, because I've also noticed that the "HaskellWiki" section of the feed you mentioned also hasn't been updated in a year.

**Comment by gbaz** [comment]
fixed by https://github.com/chrisdone/haskellnews/commit/042f11da5e96f74d9fa17384ec345e3e0f2a66a0
