### ISSUE TITLE
Rename "Core" to "Minimal"

### ISSUE THREAD

**Issue by goldfirere** [haskell-infra/hl#196]
When I view https://www.haskell.org/platform/#linux-generic, I see that I can download the "Core" Haskell Platform. This should be renamed to Minimal to be consistent with terminology used elsewhere.

**Comment by gbaz** [comment]
We went the other way 'round and renamed "minimal" to core as per the discussion here https://github.com/haskell/haskell-platform/issues/250

If anything we should probably update other terminology to use "core" -- luckily minimal/core is still relatively new (since 8.0.1) so this is a decent time to shift the name.

**Comment by goldfirere** [comment]
Yes, since posting, I've seen Core elsewhere. But not exclusively. I'm not opinionated about which it should be, but being consistent would be an improvement. Thanks!

**Comment by gbaz** [comment]
closing as fixed. feel free to reopen and comment if there's still old language we missed fixing.

**Comment by gbaz** [comment]
Actually, i note that the infamous downloads page still uses minimal rather than core, reoopening

**Comment by gbaz** [comment]
fixed in the new repo
