### ISSUE TITLE
An "advanced" purely-functional programming language

### ISSUE THREAD

**Issue by cies** [haskell-infra/hl#70]
I think advanced can mean many different things to different people. Maybe "A strongly typed..." fits better?

**Comment by chrisdone** [comment]
I think it's fine as-is.

**Comment by cies** [comment]
So what does "advanced" mean? Java is certainly advanced, Ruby and Python too.. What language is (or was, when it came out) not "advanced" in a particular aspect?

Sorry for the disruption.. Just wanted to emphasize my point. Feel free to close it :)

**Comment by chrisdone** [comment]
What does "purely-functional" mean? We can play the definition game all day like we did in May but I'll sit this one out.

**Comment by cdupont** [comment]
Purity is the most prominent feature of Haskell. It justified that I learned the language.
So without entering in the definition game, I would separate the words "purely" from "functional" to emphasis that:

    A pure functional programming language

**Comment by cies** [comment]
>  We can play the definition game all day like we did in May but I'll sit this one out.

I don't know if I said something wrong in May :)  (or I don't know this saying of the English language)

And feel free not even to "sit it out" but to close it.

Just want to say that "advanced", w/o say in which aspect and/or compared to what, is not really adding anything.

**Comment by gbaz** [comment]
We kicked this around in a haskell.org committee discussion and again on the haskell-infra channel, with ideas from just dropping "advanced" to putting in various other phrases, and none seemed a clear "winner" so it appears we're at some sort of local minima with regards to effort / payoff on the tagline. As such, closing this ticket since it seems there's not enough momentum to justify a change.
