### ISSUE TITLE
Older downloads for minimal installers.

### ISSUE THREAD

**Issue by gbaz** [haskell-infra/hl#85]
We should migrate the hosting of all minimal installers to downloads.h.o and from there allow maintainers to list older installers for posterity.

We can then link to those pages from the new www.

**Comment by chrisdone** [comment]
+1 fwiw

**Comment by lspitzner** [comment]
+1

(until fixed, maybe add a link to https://downloads.haskell.org/~platform/ somewhere at least.)

**Comment by erantapaa** [comment]
We are also tracking this issue here:

https://github.com/haskell/haskell-platform/issues/200

and the old pages are still on the website as:

https://www.haskell.org/platform/old/

so you can view the old version of the prior releases with:

https://www.haskell.org/platform/old/prior.html

I'll get a real page up soon.

**Comment by gbaz** [comment]
obsoleted by other changes  i think
